### ISSUE TITLE
Emulator path in settings is not saved unless you use the browse button

### ISSUE THREAD

**Issue by abathur8bit** [pfiscarelli/CoCo_Sprite_Compiler#1]
Go to menu **Settings > Emulators** and when you paste a path into the VCC Path, then click **Close** the path will not be saved. You have to use the browse button. I also tabbed out of the field and hit Close with the same result.

Also, when you restart the app, the path that the browse button uses is not what it is in the path field, it defaults to where CoCoCS.exe is. This makes sense if the path doesn't exist, but when I have a correct path, it should use that path instead.

**Comment by pfiscarelli** [comment]
Fixed in alpha release v0.1.9081.33620 (pushed in alpha release v0.1.9086.26496)
