### ISSUE TITLE
Emulator path warning shouldn't show all the time

### ISSUE THREAD

**Issue by abathur8bit** [pfiscarelli/CoCo_Sprite_Compiler#2]
In my case, I don't use or have the XRoar emulator, but I get a warning that the emulator can't be found every time I start the app. Perhaps the warning should be disabled if the field is empty, or better, have a checkbox that indicates the user wants to use the emulator, and if they do, show the warning.

**Comment by pfiscarelli** [comment]
Fixed in alpha release v0.1.9081.33620 (pushed in alpha release v0.1.9086.26496)
